import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :blockclock, BlockclockWeb.Endpoint,
url: [host: System.get_env("RENDER_EXTERNAL_HOSTNAME") || "localhost", port: 80],
cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#config :blockclock, BlockclockWeb.Endpoint,
#http: [port: {:system, "PORT"}],
#url: [scheme: "https", host: "floating-beyond-44064.herokuapp.com", port: 443],
#force_ssl: [rewrite_on: [:x_forwarded_proto]],
#secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE"),
#check_origin: ["http://localhost:4000/","https://floating-beyond-44064.herokuapp.com/","https://www.grandibet.com/"]
# Do not print debug messages in production


# Configure your database
#config :blockclock, Blockclock.Repo,
#adapter: Ecto.Adapters.Postgres,
#hostname: System.get_env("DATABASE_URL"),
#pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
#ssl: true
